data:
  data_dir: "data/SISO_three-masses/"
  logs_dir: "logs/"
  checkpoints_dir: "checkpoints/"
  train_test_ratio: [0.5, 0.5] # Total data points 100

architecture:
  d_model: 64
  N_stacks: 2
  h: 1
  d_ff: 32
  activation_ff: "gelu"
  dropout_rate: 0.1

training:
  # optimizer
  epochs: 20
  batch_size: 64
